import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {mountKernelPanel,kernelClient} from '../src/kernel-client.js';
test('opt-in live handlers execute real API contract without persisting bearer credentials',async()=>{
 const dom=new JSDOM('<div id="panel"></div>',{url:'http://127.0.0.1:8787/?kernel=local'});const host=dom.window.document.querySelector('#panel');const calls=[];
 const fetcher=async(path,options)=>{calls.push({path,options});return {ok:true,json:async()=>path==='/api/health'?{status:'ready',inference:false}:path==='/api/tasks'?{id:'task',status:'queued'}:{id:'task',status:options.method==='POST'?'cancelled':'succeeded'}};};
 mountKernelPanel(host,{fetcher});const token='test-live-only-token-long-000';host.querySelector('#kernel-token').value=token;const event=()=>({preventDefault(){}});await host.querySelector('#kernel-connect').onsubmit(event());assert.equal(host.querySelector('#kernel-token').value,'');assert.equal(host.querySelector('#kernel-submit').hidden,false);host.querySelector('#kernel-text').value='<unsafe>';await host.querySelector('#kernel-submit').onsubmit(event());await host.querySelector('#kernel-refresh').onclick();assert.match(host.querySelector('#kernel-status').textContent,/succeeded/);await host.querySelector('#kernel-cancel').onclick();assert.match(host.querySelector('#kernel-status').textContent,/cancelled/);assert.ok(calls.every(c=>c.options.headers.Authorization==='Bearer '+token));assert.equal(dom.window.localStorage.length,0);assert.equal(host.innerHTML.includes(token),false);host.querySelector('#kernel-disconnect').onclick();assert.equal(host.querySelector('#kernel-submit').hidden,true);assert.match(host.querySelector('#kernel-status').textContent,/Disconnected/);assert.throws(()=>kernelClient('short'),/token/);dom.window.close();
});

test('disconnect fences an in-flight authentication response',async()=>{const dom=new JSDOM('<div id="p"></div>');const host=dom.window.document.querySelector('#p');let finish;const fetcher=()=>new Promise(resolve=>{finish=resolve;});mountKernelPanel(host,{fetcher});host.querySelector('#kernel-token').value='test-stale-only-token-long-000';const pending=host.querySelector('#kernel-connect').onsubmit({preventDefault(){}});host.querySelector('#kernel-disconnect').onclick();finish({ok:true,json:async()=>({status:'ready'})});await pending;assert.equal(host.querySelector('#kernel-submit').hidden,true);assert.match(host.querySelector('#kernel-status').textContent,/Disconnected/);dom.window.close();});
