import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import * as catalog from '../src/catalog.js';
import * as core from '../src/core.js';
const source=(await readFile(new URL('../src/main.js',import.meta.url),'utf8')).split('\n').filter(line=>!line.startsWith('import ')).join('\n');
function setup(){const dom=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'https://jarvis.test/',runScripts:'outside-only'});Object.assign(dom.window,catalog,core);dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};dom.window.eval(source);return dom;}
function click(w,selector){const el=w.document.querySelector(selector);assert.ok(el,selector+' exists');el.click();}
function submit(w,id){w.document.querySelector(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
test('actual UI handlers resolve duplicates, filter, plan connectors and preserve preferences',()=>{const d=setup(),w=d.window;try{assert.match(w.document.body.textContent,/Less orchestration/);click(w,'nav [data-view="skills"]');click(w,'[data-resolve]');assert.match(w.document.body.textContent,/No capability conflicts/);const input=w.document.querySelector('#skill-search');input.value='no-match';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.match(w.document.body.textContent,/No skills found/);click(w,'nav [data-view="stack"]');click(w,'[data-adapter="openclaw"]');assert.match(w.document.querySelector('[data-adapter="openclaw"]').textContent,/Remove/);click(w,'[data-server="github"]');const stored=JSON.parse(w.localStorage.getItem('jarvis-preview-v1'));assert.deepEqual(stored.connectors,['openclaw']);assert.deepEqual(stored.plannedServers,['github']);assert.ok(!stored.enabledSkills.includes('legacy-dev'));}finally{w.close();}});
test('UI creates a simulation, handles blocker, completes and does not reopen',()=>{const d=setup(),w=d.window;try{click(w,'[data-new-task]');w.document.querySelector('#task-title').value='Verify a task';submit(w,'#task-form');click(w,'[data-action="fail"]');assert.ok(w.document.querySelector('[data-action="retry"]'));click(w,'[data-action="retry"]');for(let i=0;i<3;i++)click(w,'[data-action="next"]');assert.match(w.document.body.textContent,/Simulation finished. No real work was executed./);assert.equal(w.document.querySelector('[data-action="next"]'),null);assert.equal(JSON.parse(w.localStorage.getItem('jarvis-preview-v1')).runs[0].status,'done');}finally{w.close();}});
test('settings validates credentials, persists endpoint and reset requires confirmation',()=>{const d=setup(),w=d.window;try{click(w,'nav [data-view="settings"]');w.document.querySelector('#endpoint').value='https://user:secret@example.com';submit(w,'#settings-form');assert.match(w.document.querySelector('#settings-error').textContent,/without credentials/);w.document.querySelector('#endpoint').value='https://devhub.example/api';submit(w,'#settings-form');assert.equal(JSON.parse(w.localStorage.getItem('jarvis-preview-v1')).endpoint,'https://devhub.example/api');click(w,'[data-reset]');click(w,'[data-cancel-reset]');assert.equal(JSON.parse(w.localStorage.getItem('jarvis-preview-v1')).endpoint,'https://devhub.example/api');click(w,'[data-reset]');click(w,'[data-confirm-reset]');assert.equal(JSON.parse(w.localStorage.getItem('jarvis-preview-v1')).endpoint,'');}finally{w.close();}});
test('user-supplied task markup is escaped instead of rendered',()=>{const d=setup(),w=d.window;try{click(w,'[data-new-task]');w.document.querySelector('#task-title').value='<img src=x onerror=alert(1)>';submit(w,'#task-form');assert.equal(w.document.querySelector('img'),null);assert.match(w.document.body.textContent,/<img src=x/);}finally{w.close();}});
