import {randomUUID} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import {Store} from './store.js';
import {authorize,scope,hash,fail,terminal} from './common.js';
import {workApproval,reserveBudget} from './governance.js';
import {contextManifest} from './context.js';
import {selectSkills} from './skill-router.js';
import {workflowCatalog} from './catalog.js';
export class Kernel {
 constructor({path=':memory:',mcp,leaseMs=2000}={}){this.store=new Store(path);this.mcp=mcp;this.leaseMs=leaseMs;this.active=new Map();this.closed=false;this.recover();}
 recover(){this.store.transaction(()=>{for(const t of this.store.all()){if(terminal.has(t.status))continue;if(t.status!=='queued'){t.status=Date.now()>=t.deadlineAt?'timed_out':'failed';t.failure='Restart reconciliation: owned executor lost; no automatic retry';t.cleanup={state:t.operation==='mcp.fixture.echo'?'quarantined':'confirmed',reason:'No replay of uncertain effects'};t.epoch++;this.store.save(t,'recovery');}else if(Date.now()>=t.deadlineAt){t.status='timed_out';t.cleanup={state:'confirmed'};this.store.save(t,'deadline');}}});}
 submit(actor,input){if(this.closed)fail('closed','Kernel closed',503);const {workspace,idempotencyKey,operation='text.digest',text,delayMs=0,timeoutMs=2000,goalId=null}=input;scope(actor,actor.tenant,workspace);authorize(actor,operation);if(!['text.digest','mcp.fixture.echo'].includes(operation))fail('tool_denied','Unknown executor',403);if(typeof idempotencyKey!=='string'||idempotencyKey.length<1||idempotencyKey.length>100||typeof text!=='string'||text.length>4096||!Number.isInteger(delayMs)||delayMs<0||delayMs>500||!Number.isInteger(timeoutMs)||timeoutMs<10||timeoutMs>10000||goalId!==null&&(typeof goalId!=='string'||goalId.length>100))fail('input','Invalid bounded task input');const payload={workspace,operation,text,delayMs,timeoutMs,goalId},payloadHash=hash(payload);const routing=selectSkills(workflowCatalog(actor,workspace),{actor,workspace,capabilities:[operation],pins:['jarvis.bounded-work'],budget:512});if(routing.blocked)fail('skill_route','No eligible workflow policy',403);
 return this.store.transaction(()=>{const prior=this.store.find(actor.tenant,workspace,idempotencyKey);if(prior){if(prior.payloadHash!==payloadHash)fail('idempotency_conflict','Key already used for different payload',409);return prior;}const tasks=this.store.all();if(tasks.length>=10000)fail('capacity','Retention capacity reached',429);reserveBudget(100,tasks.filter(t=>t.tenant===actor.tenant&&!terminal.has(t.status)).length,0,1);const approval=workApproval({goalId,workspace,capability:operation},actor);const now=Date.now(),t={id:randomUUID(),tenant:actor.tenant,workspace,actorId:actor.id,idempotencyKey,payloadHash,input:payload,status:'queued',attempt:0,maxAttempts:1,epoch:0,deadlineAt:now+timeoutMs,createdAt:now,cleanup:{state:'not-started'},approval,operation,routing};this.store.insert(t);return t;});}
 read(actor,id){const t=this.store.get(id);if(!t)fail('not_found','Task not found',404);scope(actor,t.tenant,t.workspace);return {...t,events:this.store.events(id)};}
 claim(id){return this.store.transaction(()=>{const t=this.store.get(id);if(!t||t.status!=='queued')fail('lease','Task is not claimable',409);if(Date.now()>=t.deadlineAt){t.status='timed_out';t.cleanup={state:'confirmed'};this.store.save(t,'deadline');return null;}t.attempt++;t.epoch++;t.runId=randomUUID();t.leaseUntil=Date.now()+this.leaseMs;t.status='inspecting';t.cleanup={state:'pending'};this.store.save(t,'claim');return t;});}
 update(id,epoch,change,kind){return this.store.transaction(()=>{const t=this.store.get(id);if(!t||t.epoch!==epoch||terminal.has(t.status))fail('stale_lease','Stale/terminal lease',409);if(Date.now()>t.leaseUntil)fail('stale_lease','Lease expired',409);Object.assign(t,change);this.store.save(t,kind);return t;});}
 cancel(actor,id){const t=this.read(actor,id);if(terminal.has(t.status))return t;const active=this.active.get(id);if(active){active.stop='cancelled';active.controller.abort();return this.read(actor,id);}return this.store.transaction(()=>{const current=this.store.get(id);current.status='cancelled';current.cleanup={state:'confirmed',reason:'No owned execution started'};this.store.save(current,'cancelled');return current;});}
 async execute(actor,id){if(this.active.size>=1)fail('capacity','Single supervisor occupied',429);const before=this.read(actor,id);authorize(actor,before.operation);if(terminal.has(before.status))return before;const t=this.claim(id);if(!t)return this.read(actor,id);const controller=new AbortController(),active={controller,stop:null};this.active.set(id,active);const timeout=setTimeout(()=>{active.stop='timed_out';controller.abort();},Math.max(1,t.deadlineAt-Date.now()));const leaseTimer=setInterval(()=>{try{this.update(id,t.epoch,{leaseUntil:Date.now()+this.leaseMs},'lease');}catch{controller.abort();}},Math.max(10,Math.floor(this.leaseMs/3)));let result,status='succeeded',failure,cleanup={state:'confirmed',kind:'owned in-process computation'};
 try{const manifest=contextManifest([...t.routing.selected.map(s=>({id:s.id,tenant:t.tenant,workspace:t.workspace,role:'instruction',trust:'approved-skill',source:'jarvis-policy/'+s.hash,content:s.body,required:true})),{id:'intent',tenant:t.tenant,workspace:t.workspace,role:'instruction',trust:'user',source:'authenticated-task/'+t.id,content:t.input.text,required:true}],{actor,workspace:t.workspace,budget:2048});this.update(id,t.epoch,{context:manifest,status:'changing'},'changing');await delay(t.input.delayMs,undefined,{signal:controller.signal});authorize(actor,t.operation);if(Date.now()>=t.deadlineAt||controller.signal.aborted)throw new Error('Deadline/cancel before dispatch');if(t.operation==='text.digest')result={sha256:hash(t.input.text),characters:t.input.text.length,executor:'owned-text-digest-v1'};else{const receipt=await this.mcp.invoke(actor,t.workspace,{text:t.input.text},{signal:controller.signal,deadlineAt:t.deadlineAt});result=receipt.result;cleanup=receipt.cleanup;}this.update(id,t.epoch,{status:'verifying'},'verifying');if(!result)throw new Error('Missing result');
 }catch(e){failure=e.code??e.message;status=active.stop??'failed';if(t.operation==='mcp.fixture.echo'&&e.code==='mcp_cleanup')cleanup={state:'quarantined',reason:'Owned process termination uncertain'};}
 finally{clearTimeout(timeout);clearInterval(leaseTimer);this.active.delete(id);}
 if(active.stop)status=active.stop;else if(Date.now()>=t.deadlineAt)status='timed_out';this.store.transaction(()=>{const current=this.store.get(id);if(current.epoch!==t.epoch||terminal.has(current.status))return;if(Date.now()>current.leaseUntil){status='failed';failure='Lease expired; stale result discarded';result=undefined;}Object.assign(current,{status,result:status==='succeeded'?result:undefined,failure,finishedAt:Date.now(),cleanup,leaseUntil:null});this.store.save(current,'terminal');});return this.read(actor,id);
 }
 async drain(actor){for(const t of this.store.all()){if(t.status==='queued'&&t.tenant===actor.tenant&&t.actorId===actor.id&&actor.workspaces.includes(t.workspace))await this.execute(actor,t.id);}}
 async close(){this.closed=true;for(const a of this.active.values()){a.stop='cancelled';a.controller.abort();}if(this.active.size)fail('active','Await owned execution before closing store',409);this.store.close();}
}
