import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {authorize,scope,hash,fail} from './common.js';
export class McpRegistry {
 constructor(){this.servers=new Map();this.grants=new Map();}
 preview(descriptor,actor){scope(actor,descriptor.tenant,descriptor.workspace);if(!descriptor.pin||!descriptor.license||!['stdio','streamable-http'].includes(descriptor.transport))fail('mcp_descriptor','Explicit pin/license/transport required');const proposal={...descriptor,installed:false,scope:'project-only',state:'proposed',network:false,rollback:'No installation has occurred'};return {...proposal,approvalHash:hash(proposal)};}
 configureFixture(actor,workspace){scope(actor,actor.tenant,workspace);const d={id:'owned-fixture',tenant:actor.tenant,workspace,transport:'stdio',pin:hash(readFileSync(new URL('./fixture-mcp.js',import.meta.url),'utf8')),license:'MIT',state:'configured',installedExternal:false};this.servers.set(actor.tenant+'/'+workspace,d.id&&d);return {...d};}
 grant(actor,workspace,schemaHash){authorize(actor,'mcp.fixture.echo');scope(actor,actor.tenant,workspace);this.grants.set(actor.tenant+'/'+workspace+'/'+actor.id,schemaHash);}
 async invoke(actor,workspace,args,{signal,deadlineAt=Date.now()+2000,maxOutput=8192,onState=()=>{}}={}){
  authorize(actor,'mcp.fixture.echo');scope(actor,actor.tenant,workspace);const descriptor=this.servers.get(actor.tenant+'/'+workspace);if(!descriptor)fail('mcp_unconfigured','Owned fixture not configured');if(typeof args.text!=='string'||args.text.length>4096||!Number.isInteger(args.delayMs??0)||(args.delayMs??0)<0||(args.delayMs??0)>500)fail('mcp_arguments','Invalid fixture arguments');
  if(signal?.aborted||Date.now()>=deadlineAt)fail('mcp_deadline','MCP dispatch deadline elapsed');if(descriptor.pin!==hash(readFileSync(new URL('./fixture-mcp.js',import.meta.url),'utf8')))fail('mcp_pin','Fixture source changed after configuration');
  const client=new Client({name:'jarvis-kernel',version:'0.1.0'});const transport=new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('./fixture-mcp.js',import.meta.url))],stderr:'pipe',maxBufferSize:16384});transport.stderr?.resume();let cleanup={state:'not-started'},pid;
  try{onState('starting');await client.connect(transport,{timeout:Math.max(1,deadlineAt-Date.now()),signal});pid=transport.pid;cleanup={state:'pending',pid};onState('initialized');const tools=await client.listTools({}, {timeout:Math.max(1,deadlineAt-Date.now()),signal});const schemaHash=hash(tools.tools);if(this.grants.get(actor.tenant+'/'+workspace+'/'+actor.id)!==schemaHash)fail('mcp_grant','Schema-bound tool grant missing',403);onState('discovered');const result=await client.callTool({name:'echo',arguments:args},undefined,{timeout:Math.max(1,deadlineAt-Date.now()),signal});if(Buffer.byteLength(JSON.stringify(result))>maxOutput)fail('mcp_output','Output limit exceeded');onState('healthy');return {result,schemaHash,protocolVersion:client.getServerVersion(),cleanup};
  }finally{pid??=transport.pid;onState('draining');await client.close();await transport.close();let alive=false;if(pid){try{process.kill(pid,0);alive=true;}catch{}}cleanup.state=alive?'quarantined':'confirmed';onState(alive?'quarantined':'stopped');if(alive)fail('mcp_cleanup','Owned fixture cleanup uncertain',500);}
 }
 async discover(actor,workspace){authorize(actor,'mcp.fixture.echo');scope(actor,actor.tenant,workspace);if(!this.servers.has(actor.tenant+'/'+workspace))fail('mcp_unconfigured','Not configured');const c=new Client({name:'jarvis-discovery',version:'0.1.0'}),t=new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('./fixture-mcp.js',import.meta.url))],stderr:'pipe',maxBufferSize:16384});t.stderr?.resume();try{await c.connect(t,{timeout:2000});const tools=await c.listTools({}, {timeout:2000});return {tools:tools.tools,schemaHash:hash(tools.tools)};}finally{await c.close();await t.close();}}
}
