import './style.css';
import './live-entry.js';
import {integrations,skills,servers,milestones} from './catalog.js';
import {initialState,conflicts,resolveTo,createRun,advanceRun,safeEndpoint,restoreState,exportPlan,phases} from './core.js';
const storageKey='jarvis-preview-v1';
let state; try {state=restoreState(localStorage.getItem(storageKey));} catch {state=initialState();}
let view=['overview','stack','skills','runs','blueprint','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';
let skillQuery='',skillCategory='All',selectedRun=state.runs[0]?.id,toastTimer;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={overview:'◈',stack:'▤',skills:'✳',runs:'↗',blueprint:'◷',settings:'⚙'};
const labels={overview:'Overview',stack:'Your stack',skills:'Skill registry',runs:'Task lab',blueprint:'Blueprint',settings:'Workspace'};
function notice(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{notice('Browser storage unavailable. Changes remain in this tab only.');}}
function go(next){view=next;location.hash=next;render();$('#main').focus();}
function download(){const blob=new Blob([JSON.stringify(exportPlan(state),null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='jarvis-stack-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Plan exported. No credentials, installs or live connections included.');}
const badge=(text,type='')=>'<span class="badge '+type+'">'+esc(text)+'</span>';
function heading(eyebrow,title,description,action=''){return '<div class="section-heading"><div><p class="eyebrow">'+eyebrow+'</p><h1>'+title+'</h1><p class="lede">'+description+'</p></div>'+action+'</div>';}
function integrationCard(item){const added=state.connectors.includes(item.id);return '<article class="integration-card"><div class="card-top"><span class="app-symbol '+item.color+'">'+item.symbol+'</span>'+badge(item.state)+'</div><h3>'+item.name+'</h3><p class="role">'+item.role+'</p><p>'+item.description+'</p><div class="card-bottom"><a href="'+item.source+'" target="_blank" rel="noopener noreferrer">Source ↗</a><button class="text-button" data-adapter="'+item.id+'">'+(added?'Remove from plan −':'Add to plan +')+'</button></div></article>';}
function overview(){const overlap=conflicts(state.enabledSkills);return heading('YOUR ASSISTANT. ONE SYSTEM.','Less orchestration.<br><span class="serif">More possibility.</span>','A considered home for your tools, skills and execution. Bring the stack together. Keep the complexity out.', '<button class="button primary" data-new-task>＋ Try a task</button>')+
'<section class="hero-grid"><div class="architecture-panel"><div class="panel-label"><span>THE UNIFIED STACK</span>'+badge('Architecture preview','outline')+'</div><div class="orbit"><div class="orbit-ring ring-one"></div><div class="orbit-ring ring-two"></div><div class="orbit-center"><span class="jarvis-mark">J<span>•</span></span><strong>JARVIS</strong><small>One control plane</small></div><div class="orbit-node node-a orange"><span>OC</span><strong>OpenClaw</strong><small>Orchestrate</small></div><div class="orbit-node node-b lime"><span>gm</span><strong>gm</strong><small>Deliver</small></div><div class="orbit-node node-c purple"><span>ƒ</span><strong>Freddie</strong><small>Execute</small></div><div class="orbit-node node-d blue"><span>⌘</span><strong>MCP</strong><small>Connect</small></div><svg class="orbit-lines" viewBox="0 0 640 290" aria-hidden="true"><path d="M120 95 Q240 30 320 145 M520 95 Q420 30 320 145 M120 235 Q220 260 320 145 M520 235 Q420 260 320 145"/></svg></div><div class="architecture-caption"><span class="dot amber"></span> Interfaces planned. No engines connected.</div></div><div class="principle-panel"><p class="eyebrow">BUILT TO FINISH</p><h2>Intelligence without<br>the infinite loop.</h2><p>One task owner. Clear boundaries. An ending that actually ends.</p><ol class="flow-list"><li><span>01</span><div><strong>Inspect</strong><small>Understand once. Scope the work.</small></div><b>↗</b></li><li><span>02</span><div><strong>Change</strong><small>Do the work. Keep the checkpoint.</small></div><b>↗</b></li><li><span>03</span><div><strong>Verify</strong><small>Real evidence. Bounded retries.</small></div><b>↗</b></li><li><span>04</span><div><strong>Finish</strong><small>Deliver. Stop. No recursive handoff.</small></div><b>✓</b></li></ol><button class="text-button" data-view="blueprint">Read the architecture →</button></div></section>'+
'<section class="stats-grid"><article><p>PLANNED ADAPTERS</p><strong>'+state.connectors.length+'<span> / 4</span></strong><small>No live integrations</small></article><article><p>ENABLED SAMPLE SKILLS</p><strong>'+state.enabledSkills.length+'<span> / '+skills.length+'</span></strong><small>Local registry configuration</small></article><article><p>CAPABILITY OVERLAPS</p><strong class="'+(overlap.length?'amber-text':'mint-text')+'">'+overlap.length+'</strong><button class="text-button" data-view="skills">'+(overlap.length?'Review conflicts →':'Registry is unambiguous →')+'</button></article><article><p>LOCAL SIMULATIONS</p><strong>'+state.runs.length+'</strong><small>Not real agent executions</small></article></section>'+
'<section><div class="subheading"><div><p class="eyebrow">BETTER TOGETHER</p><h2>Your stack, with a shared language.</h2></div><button class="text-button" data-view="stack">Configure stack →</button></div><div class="integration-grid">'+integrations.map(integrationCard).join('')+'</div></section>'+
'<div class="devhub-strip"><span class="hub-icon">↗</span><div><h3>Built for your DevHub.</h3><p>One versioned handoff. Project context in, verified outcomes out.</p></div>'+badge('Contract pending')+'<button class="button secondary" data-export>Export stack plan ↗</button></div>';}
function stack(){return heading('COMPOSABLE, NOT COMPLICATED','The right tool.<br><span class="serif">One place to start.</span>','Choose the adapters in your plan. Adding one does not install software, grant permissions or establish a connection.')+'<div class="integration-grid">'+integrations.map(integrationCard).join('')+'</div><div class="subheading"><div><p class="eyebrow">TOOLS WITH BOUNDARIES</p><h2>MCP installation planner</h2></div>'+badge('Proposal only','outline')+'</div><div class="server-list">'+servers.map(s=>'<article class="server-row"><span class="server-icon">⌘</span><div><h3>'+s.name+'</h3><p>'+s.description+'</p><small>'+s.transport+' · '+s.scope+'</small></div><button class="button secondary" data-server="'+s.id+'">'+(state.plannedServers.includes(s.id)?'Remove proposal':'Include in plan')+'</button></article>').join('')+'</div><div class="callout"><strong>Nothing runs behind your back.</strong><p>A production installer must verify packages, pin versions, preview permissions and changes, capture approval, and retain a rollback record. This frontend only exports the proposal.</p><button class="text-button" data-export>Download installation plan →</button></div>';}
function skillPage(){const overlap=conflicts(state.enabledSkills);return heading('ONE CAPABILITY. ONE CLEAR OWNER.','Skills, without<br><span class="serif">the overlap.</span>','These are sample manifests, not a scan of your installed skills. Resolve competing capabilities in the local plan without deleting upstream files.')+(overlap.length?'<div class="conflict-banner"><span>!</span><div><strong>'+overlap.length+' overlapping capabilities</strong><p>'+overlap.map(c=>esc(c.capability)).join(' · ')+' — gm and the example legacy workflow both claim ownership.</p></div><button class="button primary" data-resolve>Keep gm as canonical</button></div>':'<div class="success-banner">✓ No capability conflicts in your current plan. Disabled skills remain available below.</div>')+'<div class="filter-toolbar"><label class="search-field"><span>⌕</span><input id="skill-search" type="search" placeholder="Find a skill or capability…" value="'+esc(skillQuery)+'" aria-label="Find a skill"></label><label><span class="sr-only">Skill category</span><select id="category">'+['All','Development','Knowledge','Quality','Tools','Delivery'].map(c=>'<option '+(skillCategory===c?'selected':'')+'>'+c+'</option>').join('')+'</select></label><span id="skill-count" class="muted"></span></div><div id="skill-results" class="skills-grid"></div>';}
function skillResults(){const filtered=skills.filter(s=>(skillCategory==='All'||s.category===skillCategory)&&[s.name,s.description,...s.capabilities].join(' ').toLowerCase().includes(skillQuery.toLowerCase()));$('#skill-count').textContent=filtered.length+' skills';$('#skill-results').innerHTML=filtered.length?filtered.map(s=>{const enabled=state.enabledSkills.includes(s.id);return '<article class="skill-card"><div class="card-top"><span class="skill-glyph">'+(s.id==='gm'?'gm':'✳')+'</span><button class="toggle" role="switch" aria-checked="'+enabled+'" aria-label="Enable '+esc(s.name)+'" data-skill="'+s.id+'"><span></span></button></div><h3>'+s.name+(s.preferred?' <span class="recommended">CANONICAL</span>':'')+'</h3><small>'+s.vendor+' · '+s.category+'</small><p>'+s.description+'</p><div class="capabilities">'+s.capabilities.map(c=>'<code>'+c+'</code>').join('')+'</div></article>';}).join(''):'<div class="empty-state"><h3>No skills found</h3><p>Try a different capability or category.</p></div>';}
function runsPage(){const run=state.runs.find(r=>r.id===selectedRun)||state.runs[0];if(run)selectedRun=run.id;return heading('A LAB, NOT A LIVE AGENT','Work that knows<br><span class="serif">when to stop.</span>','Exercise the proposed lifecycle locally. No model, shell command, repository change or agent is launched.','<button class="button primary" data-new-task>＋ New simulation</button>')+'<div class="run-layout"><aside class="run-list"><p class="eyebrow">LOCAL SIMULATIONS</p>'+(state.runs.length?state.runs.map(r=>'<button class="run-item '+(r.id===selectedRun?'active':'')+'" data-run="'+r.id+'"><span>'+esc(r.title)+'</span><small>'+r.phase+' · '+r.status+'</small></button>').join(''):'<p class="muted">Your first simulation starts here.</p>')+'</aside><section class="run-detail">'+(run?runDetails(run):'<div class="empty-state"><span class="empty-glyph">↗</span><h2>A clear beginning.<br>A definite finish.</h2><p>Try a bounded task lifecycle before connecting any execution engine.</p><button class="button secondary" data-new-task>Create a simulation</button></div>')+'</section></div>';}
function runDetails(r){const terminal=['done','cancelled','timed_out'].includes(r.status);return '<div class="card-top">'+badge('SIMULATED','outline')+badge(r.status,r.status==='done'?'green':'')+'</div><h2>'+esc(r.title)+'</h2><p class="muted">Retry budget '+r.attempts+' / '+r.maxAttempts+' · deadline '+new Date(r.deadline).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' · checked on each action</p><div class="phase-track">'+phases.map((p,i)=>'<div class="'+(p===r.phase?'current':phases.indexOf(r.phase)>i?'complete':'')+'"><span>'+String(i+1).padStart(2,'0')+'</span><strong>'+p+'</strong></div>').join('')+'</div><div class="run-actions">'+(terminal?'<p class="mint-text">'+(r.status==='done'?'Simulation finished. No real work was executed.':'Stopped. This task will not restart automatically.')+'</p>':(r.status==='blocked'?'<button class="button primary" data-action="retry" '+(r.attempts>=r.maxAttempts?'disabled':'')+'>Explicit retry</button>':'<button class="button primary" data-action="next">'+(r.phase==='verify'?'Finish simulation ✓':'Advance to '+phases[phases.indexOf(r.phase)+1]+' →')+'</button><button class="button secondary" data-action="fail">Simulate blocker</button>')+'<button class="text-button danger" data-action="cancel">Cancel task</button>')+'</div><h3 class="event-heading">Checkpoint log</h3><ol class="event-log">'+r.events.map(e=>'<li><time>'+new Date(e.at).toLocaleTimeString()+'</time><span>'+esc(e.text)+'</span></li>').join('')+'</ol>';}
function blueprint(){return heading('ONE REPO. AN EXPLICIT PATH.','Build the system.<br><span class="serif">Not another wrapper.</span>','A frontend today. A durable, capability-aware assistant control plane next. No claim that a UI alone fixes runtime behavior.')+'<div class="blueprint-layout"><div class="roadmap">'+milestones.map(m=>'<article class="milestone"><span class="milestone-num '+(m.done?'done':'')+'">'+m.stage+'</span><div>'+badge(m.status,m.done?'green':'')+'<h2>'+m.title+'</h2><p>'+m.body+'</p></div></article>').join('')+'</div><aside class="guardrails"><p class="eyebrow">NON-NEGOTIABLES</p><h2>Good boundaries<br>make better agents.</h2>'+['One durable task owner','No recursive delegation chains','A deadline for every process','Human approval for privilege changes','Capabilities, not duplicate skill names','Secrets stay out of the browser','Evidence before success claims','Completion is a terminal state'].map(t=>'<p><span>↗</span>'+t+'</p>').join('')+'<a class="text-button" href="https://github.com/SolutionsAsService/JARVIS/blob/main/docs/PLAN.md" target="_blank" rel="noopener noreferrer">Full implementation plan ↗</a></aside></div>';}
function settings(){return heading('LOCAL-FIRST PREVIEW','Your workspace.<br><span class="serif">Your boundaries.</span>','Preferences live in this browser only. No secrets, authentication or live DevHub connection is stored here.')+'<div class="settings-grid"><form id="settings-form" class="settings-card"><h2>DevHub handoff</h2><p>This endpoint is descriptive configuration only. Save does not contact it.</p><label for="endpoint">Proposed DevHub base URL</label><input id="endpoint" type="url" value="'+esc(state.endpoint)+'" placeholder="https://your-devhub.example"><small>HTTPS, or HTTP localhost. Do not include tokens, passwords or query strings.</small><button class="button primary" type="submit">Save endpoint</button><p id="settings-error" class="form-error" role="alert"></p></form><div class="settings-card"><h2>Portable by design</h2><p>Export the selected adapters, skill ownership and MCP proposals as a versioned JSON plan. It contains no execution credentials.</p><button class="button secondary" data-export>Export stack plan ↗</button><hr><h3>Reset the local preview</h3><p>Clears this site’s saved sample tasks and configuration. Does not affect installed software.</p><button class="text-button danger" data-reset>Reset preview data</button></div></div>';}
function render(){const content={overview,stack,skills:skillPage,runs:runsPage,blueprint,settings}[view]();$('#app').innerHTML='<aside class="sidebar"><a class="brand" href="#overview" aria-label="JARVIS overview"><span class="brand-glyph">J<span>•</span></span><span>JARVIS<small>ASSISTANT OS</small></span></a><div class="workspace-label"><span class="workspace-icon">S</span><div>SolutionsAsService<small>Personal workspace</small></div><span>⌄</span></div><p class="nav-label">WORKSPACE</p><nav aria-label="Main navigation">'+Object.keys(labels).map(k=>'<a href="#'+k+'" data-view="'+k+'" aria-label="'+labels[k]+'" class="nav-item '+(view===k?'selected':'')+'" '+(view===k?'aria-current="page"':'')+'><span aria-hidden="true">'+icons[k]+'</span>'+labels[k]+(k==='skills'&&conflicts(state.enabledSkills).length?'<b>'+conflicts(state.enabledSkills).length+'</b>':'')+'</a>').join('')+'</nav><div class="sidebar-bottom"><div class="preview-note"><span class="dot amber"></span><strong>Local preview</strong><p>Real interface.<br>Integrations not connected.</p></div><a href="https://github.com/SolutionsAsService/JARVIS" target="_blank" rel="noopener noreferrer">GitHub repository ↗</a><div class="profile"><span>SA</span><div>SolutionsAsService<small>Workspace owner</small></div></div></div></aside><div class="workspace-main"><header class="topbar"><div><span>Workspace</span><b>/</b><strong>'+labels[view]+'</strong></div><div class="topbar-actions">'+badge('FRONTEND PREVIEW','outline')+'<button class="text-button" data-export aria-label="Export stack plan">Export plan ↗</button></div></header><main id="main" tabindex="-1">'+content+'<footer><span>JARVIS <b> / </b> An intelligent stack, deliberately composed.</span><span>v0.1 · Frontend foundation</span></footer></main></div><dialog id="task-dialog"><form id="task-form"><div class="card-top"><p class="eyebrow">LOCAL TASK LAB</p><button class="icon-button" type="button" data-close-dialog aria-label="Close">×</button></div><h2>What will you work on?</h2><p>Try the workflow. This creates a simulation only — it won’t launch an agent or change a repository.</p><label for="task-title">Task objective</label><input id="task-title" name="title" required minlength="4" maxlength="180" placeholder="e.g. Verify a scoped repository change" autocomplete="off"><p class="form-error" id="task-error" role="alert"></p><div class="dialog-policy"><span>↗ One task owner</span><span>◷ 10-minute budget</span><span>↻ 2 explicit retries</span></div><button class="button primary" type="submit">Create simulation →</button></form></dialog><dialog id="reset-dialog"><h2>Reset this preview?</h2><p>This removes only JARVIS preview data saved in this browser. No installed skills or external tasks are affected.</p><div class="run-actions"><button class="button secondary" data-cancel-reset>Keep my data</button><button class="button primary" data-confirm-reset>Reset local data</button></div></dialog>';if(view==='skills')skillResults();}
document.addEventListener('click',event=>{const el=event.target.closest('button,a');if(!el)return;try{
 if(el.dataset.view){event.preventDefault();go(el.dataset.view);}
 if(el.hasAttribute('data-export'))download();
 if(el.hasAttribute('data-new-task')){$('#task-dialog').showModal();$('#task-title').focus();}
 if(el.hasAttribute('data-close-dialog'))$('#task-dialog').close();
 if(el.dataset.adapter){state.connectors=state.connectors.includes(el.dataset.adapter)?state.connectors.filter(x=>x!==el.dataset.adapter):[...state.connectors,el.dataset.adapter];save();render();notice('Adapter plan updated. No live connection was made.');}
 if(el.dataset.server){state.plannedServers=state.plannedServers.includes(el.dataset.server)?state.plannedServers.filter(x=>x!==el.dataset.server):[...state.plannedServers,el.dataset.server];save();render();notice('MCP proposal updated. Nothing installed.');}
 if(el.dataset.skill){state.enabledSkills=state.enabledSkills.includes(el.dataset.skill)?state.enabledSkills.filter(x=>x!==el.dataset.skill):[...state.enabledSkills,el.dataset.skill];save();render();document.querySelector('[data-skill="'+el.dataset.skill+'"]').focus();}
 if(el.hasAttribute('data-resolve')){state.enabledSkills=resolveTo(state.enabledSkills,'gm');save();render();notice('gm owns repo.change and repo.verify. Legacy sample disabled, not deleted.');}
 if(el.dataset.run){selectedRun=el.dataset.run;render();}
 if(el.dataset.action){state.runs=state.runs.map(r=>r.id===selectedRun?advanceRun(r,el.dataset.action):r);save();render();}
 if(el.hasAttribute('data-reset'))$('#reset-dialog').showModal();
 if(el.hasAttribute('data-cancel-reset'))$('#reset-dialog').close();
 if(el.hasAttribute('data-confirm-reset')){state=initialState();selectedRun=null;save();render();notice('Local preview reset.');}
}catch(error){notice(error.message);}});
document.addEventListener('input',e=>{if(e.target.id==='skill-search'){skillQuery=e.target.value;skillResults();}});
document.addEventListener('change',e=>{if(e.target.id==='category'){skillCategory=e.target.value;skillResults();}});
document.addEventListener('submit',e=>{if(e.target.id==='task-form'){e.preventDefault();try{const run=createRun($('#task-title').value);state.runs=[run,...state.runs].slice(0,50);selectedRun=run.id;save();go('runs');notice('Local simulation created. No agent launched.');}catch(err){$('#task-error').textContent=err.message;}}if(e.target.id==='settings-form'){e.preventDefault();try{state.endpoint=safeEndpoint($('#endpoint').value);save();$('#settings-error').textContent='';notice('Endpoint saved to the local plan. Not connected.');}catch(err){$('#settings-error').textContent=err.message;}}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(labels[next]&&next!==view){view=next;render();}});
render();
